/**le
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f407xx.h>
#include <stm32f407xx_gpio_driver.h>

void delay(void){
	for(int32_t i=0; i<500000; i++);
}

int main(void)

{
	GPIO_Handle_t led_GPIO;
	led_GPIO.pGPIOx = GPIOD;
	led_GPIO.GPIO_PinConfig.GPIO_PinMode 		= GPIO_MODE_OUT;
	led_GPIO.GPIO_PinConfig.GPIO_PinNumber		= GPIO_PIN_NO_12;
	led_GPIO.GPIO_PinConfig.GPIO_PinOpType		= GPIO_OP_TYPE_PP;
	led_GPIO.GPIO_PinConfig.GPIO_PinPuPdControl	= GPIO_NO_PUPD;
	led_GPIO.GPIO_PinConfig.GPIO_PinSpeed		= GPIO_SPEED_FAST;

	GPIO_PeriClockControl(GPIOD, ENABLE);

	GPIO_Init(&led_GPIO);
	led_GPIO.GPIO_PinConfig.GPIO_PinNumber		= GPIO_PIN_NO_13;
	GPIO_Init(&led_GPIO);
	led_GPIO.GPIO_PinConfig.GPIO_PinNumber		= GPIO_PIN_NO_14;
	GPIO_Init(&led_GPIO);
	led_GPIO.GPIO_PinConfig.GPIO_PinNumber		= GPIO_PIN_NO_15;
	GPIO_Init(&led_GPIO);

	while(1){
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
		delay();
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_13);
		delay();
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_13);
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_14);
		delay();
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_14);
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_15);
		delay();
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_15);
	}
	return 0;
}
